#!/bin/bash

if [ $(id -u) == 0 ]; then
    echo -e "\e[1m\e[32mInstalling mkExeDesktopShortcut.\e[0m"
    echo -en "\e[1m\e[1;33m"; cp -rv ./usr /
else
    echo -e "\e[1m\e[31mPlease run the install script as root.\e[0m"
    exit
fi

echo -e "\e[1m\e[32mFinished installation.\e[0m"
